# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
